### ISSUE TITLE
Unnecessary space at footer

### ISSUE THREAD

**Issue by Abhii5496** [Vedant-Panchal/FlaminUI#23]
![image](https://github.com/user-attachments/assets/e74b5b17-ae7d-4a61-a657-6626869334d7)

if its okay i can fix it.

**Comment by Vedant-Panchal** [comment]
How is that possible?
![image](https://github.com/user-attachments/assets/8cb8316b-5e88-4d76-bfe3-53386d2bb4ac)

**Comment by Abhii5496** [comment]
![image](https://github.com/user-attachments/assets/9690cff0-7221-4341-9407-8ceade4f642a)
i dont know how , but its there.

**Comment by Vedant-Panchal** [comment]
Yeah i found it, you can fix it if you can

**Comment by ni3rav** [comment]
this issue only seems to be coming up on chromium based browsers
@Abhii5496 can you please confirm this by testing it on firefox ?
on my machine, the page looks fine on firefox
